### ISSUE TITLE
I've built set of scripts for using Guacamole/tomcat/nginx/mysql for html5 remote desktop to lxd

### ISSUE THREAD

**Issue by bmullan** [subutai-io/peer-os#1878]
I'm not sure if this could be of use to Subutai Social but I've built a set of scripts to auto-magically build/install Guacamole (http://guacamole.incubator.apache.org/), Nginx, Tomcat, Mysql and XRDP onto Ubuntu 16.04 and hosted LXD containers (each of which also run XRDP on that machine host.

Guacamole supports several protocols including RDP, VNC, SSH etc but I've been using RDP thus my use of XRDP (via NeutrinoLabs XRDP/XORGXRDP implementation - https://github.com/neutrinolabs/xrdp/wiki) 

A single Guacamole instance can act as a gateway to **_many_** remote desktop "server" machines/containers and it supports multi-tenancy easily.

Per Guacamole's website:
_
> Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH.
> 
> We call it clientless because no plugins or client software are required.
> 
> Thanks to HTML5, once Guacamole is installed on a server, all you need to access your desktops is a web browser.
_

I've used this to install the remote desktops on  locally, on VMs locally, on AWS and on Digital Ocean cloud instances.   Performance is very good, good enough to watch Youtube video's using the remote desktop Web Browser via my local web browser with solid audio/video.

Anyway, I have all the build/install scripts on Github so if it would fit into the Subutai Social concept feel free to explore using it.   This could add a Subutai HTML5 web browser capable Remote Desktop capability.

https://github.com/bmullan/CIAB-Guacamole-Remote-Desktop

Brian

**Comment by samsonbek** [comment]
@bmullan this is really cool! It might be very useful for Subutai Social. We never considered running desktop containers. Our focus was more towards the server side stack.

After your post, I can see myself using something like this.  I'm sure many people would have such a need. It would be nice if a user can add a desktop container to an environment and be able to access it at the press of a button.

Couple of questions:

1. There needs to be a Desktop container running inside the environment with an RDP|VNC|SSH service on it correct? What are the configuration options and requirements for the Desktop container instance?
2. To access the container's desktop from the outside, the environment will need a Guac server container running inside on the same VPN as the desktop containers correct?
3. Using your scripts will be able to easily assemble the Guac server container in #2?
4. If you can assist us with creating an example environment, we can see how we can integrate this as a first class feature of Subutai Social. Meaning when desktop containers are present we can provide a one press option that automatically installs the Guac server into the environment and exposes the needed ports to make this all work nicely. Would you be willing to help us out so we can take it from there?

Thanks,
Abdysamat

**Comment by bmullan** [comment]
I did a youtube video to show the installation on an AWS ubuntu server instance:

https://www.youtube.com/watch?v=GlzSKrIGQZ8&t=66s

In my scipts you start with an ubuntu 16.04 server (somewhere) locally, vm or in cloud.

You tar up the installation files and scp them to the server.

You create a user acct on that server for the installer  (re you).

The scripts by default assume they are being run from /opt/ciab so you need to create that directory & chown ownership to the "user account" you created.

copy the scp'd tar.gz to /opt/ciab then untar it

chmod +x *.sh

then start the installation off with

cd /opt/ciab
sudo ./setup-guacamole.sh

from there just follow the instructions.   

Each script will end with instructions saying what to do next.

The full installation of the guacamole, nginx, tomcat, mysql xrdp and the MATE desktop environment in the "HOST" and if you choose to also do the optional 2 LXD containers takes about an hour.

Using my scripts the Host Server is running the guacamole, nginx, tomcat, mysql and XRDP/X11XRDP as well as the MATE desktop environment.

The 2 LXD containers only have the MATE desktop environment running as well as their own XRDP/X11RDP.

NOTE 1:  
NeutrinoLab's has updated XRDP considerably to XRDP v0.9.2 and has eliminated the need for the X11XRDP module by replacing it with XORGXRDP.    My scripts in Github do NOT have that yet although I do have it working here ... just haven't had the time to upload the new scripts.

To answer your questions:

re 1 - the LXD containers all need to run Mate or XFCE or there are some other alternatives like LXDE and they each need to have XRDP/X11RDP installed/running 

My scripts use RDP as it supports encryption & I believe is supposed to be faster than VNC.  It also supports audio where I am not sure VNC does.

re 2 - For my scripts the Guacamole server runs on the HOST server for the LXD containers.    This doesn't need to be the case but changing it would mean changing the default LXDBR0 bridge setup.   It also would be problematic for Cloud environments because for instance on AWS you only get 1 IP for your AWS instance and the Hosted LXD containers would not get a globally accessible IP via AWS assigned to them.   So by having the Guacamole Proxy Server running on the HOST you only need to point your browser to the host (example:   https://102.65.31.222/guacamole) to acccess the guacamole signin, authenticate there then be presented with any/all Desktop environments the "admin" has configured or assigned to you.   In my scripts this could be any/all of the Mate Desktops on the Host or CN1 or CN2 LXD containers.    Those containers IP addresses are whatever you have setup for that local LXD DNSMASQ to hand out.

re 3 - the Guacamole servers don't run in the containers only in the HOST server

re 4 - I can spin up an AWS or Digital Ocean Server and install of the above so you all could check it out and see how it works.    We could have a google hangout going simultaneously so we could talk & ask/answer questions ? 

NOTE:   In the past I've created a "full mesh VPN" connecting the LXDBR0 bridges on ... local servers, AWS servers and DIgital Ocean servers.   I also setup a single DHCP/DNSMASQ so all the LXD containers on any server got a 10.x.x.x IP address out of the same 10.x.x.x address pool.

With all of the LXD containers on all of the servers on the same Layer 2 network they then could all "talk" to each other.

So remote desktop'ing to any of them was the same as remote desktop'ing to a local machine. 

Brian

**Comment by bmullan** [comment]
I should add this comment...

Since Subutai works with LXD already you know that you can copy an existing LXD container to other LXD server hosts anywhere on the internet/network if so setup.

So just like I do in my scripts I really only create one LXD Mate Desktop container with XRDP,  then CLONE it to make the 2nd.   You could just as easily do that a 100 times or and/or copy the orig CN1 container to a different LXD server somewhere then clone a whole set of more LXD Mate Desktop containers... !

**Comment by bmullan** [comment]
I used the scripts to build a new remote desktop Ubuntu 16.04 server on AWS
last nite.

I've created a guest account & password so if you'd like to login and see
how it works with the Mate Desktop on the Host and in the 2 LXD containers
(CN1 and CN2) then send me an email with your email address and I will
forward you the Login ID and password.

Also, I need to know when you want to access it and try things out as I
won't turn it on in AWS until that time and will turn it off after you are
finished looking.

bmullan.mail@gmail.com

Brian

**Comment by samsonbek** [comment]
Thanks Brian, I logged in into your Guacamole server and saw how it works.

I'll try to install Guacamole into Subutai conatainer using your scripts. Probably we also may create a Subutai Plugin for it and install it on Subutai Peer itself (host) and create accounts for environment owners. Will let you know results.

**Comment by bmullan** [comment]
The guacamole proxy management/admin interface requires a little
familiarity so you can read up on it at the guacamole web site:

https://guacamole.incubator.apache.org/doc/gug/

You can also get some sense of it by reading through the PDF I included in
my github.

https://github.com/bmullan/CIAB-Guacamole-Remote-Desktop/blob/master/README.pdf

Installing the entire script set in a container will require some thought
on audio as I said that is still one sticking point with me in the
containers ... as I said audio works with pulseaudio but a user's HOST
session has to be left active or audio in the container doesn't work.

You can access the containers for desktop use though and everything else
seems to be okay.

Let me know if you have any questions.

Brian


On Fri, Jun 30, 2017 at 6:54 AM, Abdysamat Mamutov <notifications@github.com

**Comment by bmullan** [comment]
Alsp wait till at least next week & I will update a couple of the files in
the github to reflect changes in guacamole & xrdp..!

Brian

**Comment by samsonbek** [comment]
ok.

**Comment by bmullan** [comment]
Another note...

If for Subutai you could take my scripts and just install the:

setup-guacamole.sh
and
setup-nginx.sh

on any server... doesn't have to be one with the LXD containers

The LXD "desktop" containers on other servers (anywhere) can be configured
as "connections" in the guacamole admin console by using the IP  addresses
of those remote LXD containers assuming the container addresses are
globally accessible (re not isolated 10.x.x.x).   That would take a diif
LXD bridge setup than the default.

But the 2 scripts above do setup guacamole, nginx, tomcat & mysql so there
is a working guacamole web proxy.

**Comment by bmullan** [comment]
However the setup-guacamole.sh script is one of the files I'd like to
update on github this weekend.

Brian

**Comment by bmullan** [comment]
Abdysamat

I just spent the last few hours installing the new scripts on a 2nd AWS
instance and testing it out.
Everything seems to be working so I replaced the old files on Github with
the new updated ones that include installation of the latest Guacamole
(v0.9.12) and the latest XRDP (v0.9.2)

Brian

**Comment by zubaidullo** [comment]
@bmullan thanks for your idea, we started working on this feature. 
Now we're researching and picking up the best option to implement.

**Comment by zubaidullo** [comment]
Any research and implementation information related to this issue can be found here: https://github.com/subutai-io/base/wiki/Remote-desktop-capability-with-Subutai-containers

**Comment by zubaidullo** [comment]
According to this issue, Subutai Remote desktop management feature implemented.
