### ISSUE TITLE
E2E plugin for firefox spins endlessly

### ISSUE THREAD

**Issue by bmullan** [subutai-io/peer-os#1879]
The E2E plugin for chrome worked with Chromium fine after I entered password & confirmed password.

However, E2E plugin for Firefox just had a spinner goinf for maybe five minutes before I just killed it.

Ubuntu 16.04, firefox 54

**Comment by zubaidullo** [comment]
@bmullan thanks, I will try to reproduce and work on it

**Comment by zubaidullo** [comment]
This issue appears after version FF 50, which is released on November 15, 2016

**Comment by akarasulu** [comment]
What's the status @zubaidullo? ... I'm having the same problem.

**Comment by zubaidullo** [comment]
![a0ede774-111d-48c1-93a1-1d83daac15c1_1024](https://user-images.githubusercontent.com/4469949/28553947-529df00c-7118-11e7-9501-b8f55accb557.jpg)

**Comment by zubaidullo** [comment]
According to this issue, we have refactored FireFox plugin, using the latest APIs from FF.
