### ISSUE TITLE
for a test server setup how to remove subutai from host & restart from scratch

### ISSUE THREAD

**Issue by bmullan** [subutai-io/peer-os#2040]
I have an ubuntu 16.04 Desktop system machine, i7, 32G ram, 1TB SSD

note:   just fyi but I have used LXD extensively since it came out and prior to that used LXC

A month ago I'd installed subutai on my  this machine and **at that time** the online documentation and the creation process for a "test" system were very different than now.

At that time the instructions to create test system installed an virtualbox ubuntu VM with a "peer" setup in it.

The instructions also had me install several components on my "host".

Now I see WIKI the documentation has been updated so the user needs to create their own Ubuntu server VM in virtualbox and then use SNAPD to install the subutai peer components.    

I deleted my old Virtualbox VM.

_Now I want to remove the  old Subutai components from my Host Desktop machine also and do a clean start from scratch for a Test system of both the Host & the Peer._

I have 2 questions:

1. What do I have to do to remove the subutai components from my Host desktop system.   The old Online documentation if I remember right gave the instructions of what cmds to run.   But that seems gone now on the new/updated Wiki.

2. Also, I've been unable to find on the new/updated wiki any documentation about what I need to download (if anything ??) to my Host Desktop machine so it can talk to the new Virtualbox SNAPD Subutai Peer I want to setup.

thanks
brian

**Comment by crioto** [comment]
Hello Brian,
If you installed subutai with launcher you need to remove `/opt/subutai` directory completely
Also you need to look for `p2p`, `subutai-tray` and `SubutaiTray` inside /usr/bin and delete them if any. 
Also p2p.service systemd unit needs to be removed.

**Comment by bmullan** [comment]
Thanks Mikhail...

That seems to have removed everything.

Now my final question again deals with the new/updated WIKI documentation.

No where do I find any info about where to download/install  the subutai
p2p, subutai-trai subutai launcher now for the HOST of a test setup ?

I looked here:

https://github.com/subutai-io/base/wiki/Test-Server-Preparation

and I looked here:

https://subut.ai/installation.html

The only thing I see either of those talk about is the installation of the
PEER ?

Did I miss something or a link to something about installing the subuntai
for the host ?

thanks

Brian


On Sep 25, 2017 11:59 AM, "Mikhail Savochkin" <notifications@github.com>
wrote:

Hello Brian,
If you installed subutai with launcher you need to remove /opt/subutai
directory completely
Also you need to look for p2p, subutai-tray and SubutaiTray inside /usr/bin
and delete them if any.
Also p2p.service systemd unit needs to be removed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/subutai-io/base/issues/2040#issuecomment-331928068>,
or mute
the thread

**Comment by bmullan** [comment]
Ignore my last comment... now I see that the info is documented here:

https://subut.ai/installation.html

It's just not clearly separated from the instructions above it related to installing the PEER components.

Perhaps your TEST setup documentation should clearly delinate what goes in the VM and what goes onto the HOST ?   Especially for those newbies like myself.

Thanks Brian

**Comment by crioto** [comment]
Thanks Brian.

New installation scheme does not involves creation of virtual machine and designed to install everything on your host. When you complete installation, subutai will be able to create containers right on your host machine (previously this was done only inside VirtualBox VM). 
So, basically, everything described on this page is for host machine, not for VM (however, the same steps can be made inside VM with any OS that supports snapd).

**Comment by akarasulu** [comment]
> Perhaps your TEST setup documentation should clearly delinate what goes in the VM and what goes onto the HOST ? Especially for those newbies like myself.

@bmullan thanks for the great feedback. I'll make those recommended changes.

[OT] @bmullan you had previously inquired about setting up a Hub for your university. Please get in touch with me at akarasulu AT optdyn DOT com to accommodate.

**Comment by Dilshat** [comment]
root@subutai:~# umount /var/snap/subutai/common/lxc 
root@subutai:~# snap remove subutai

**Comment by Dilshat** [comment]
Not actual now after migration
