### ISSUE TITLE
Allow allocation of 100% of memory and 100% cores on subutai

### ISSUE THREAD

**Issue by ghost** [subutai-io/peer-os#2149]
Allow allocation of 100% of memory and 100% cores on subutai

Noticed that I only have 4GB available to subutai on hub.

I have 32, would like to allocate all of it to subutai.

Installed through vagrant in virtualbox.

**Comment by Gr1dd** [comment]
Also I have a feature request!

Any way I can view the hub status for various things?

Like docker conversions.
Github/apt pulls and conversions etc.

Trying to convert my docker container here: gr1dd/nemochain:latest

Pulls fine on my debian system, curious to see what will happen. Seeing a live conversion log would be amazing, but a status page could benefit everyone probably 📦

**Comment by Gr1dd** [comment]
Moving my dockerfile to this now:
```
FROM haskell:latest

EXPOSE 8000/udp

EXPOSE 8000

EXPOSE 3000

EXPOSE 3001

EXPOSE 3002

EXPOSE 3003

EXPOSE 3004

EXPOSE 3005

RUN apt-get update

RUN apt-get --assume-yes install libpq-dev build-essential

RUN mkdir /NemoChain

WORKDIR /NemoChain

ADD . /NemoChain

RUN stack setup

RUN stack build

CMD ["stack", "exec", "nemochain"]
```


Is there something I'm missing by chance :paintbrush: 

Makes me wish there was a cancel conversion button/re-run conversion on the docker image upload on kurjun. I don't want to spam a bunch of products that are duplicate and won't load. xD Especially if you scale very large.

**Comment by Dilshat** [comment]
@Gr1dd Hi!
For Hub related issues we have this repo https://github.com/subutai-io/hub/issues
You can file issues there

**Comment by Dilshat** [comment]
We use predefined sizes for containers: TINY, SMALL, MEDIUM, LARGE, HUGE.
The Subutai containers operate within the resource constraints imposed by this range.
The limits apply to % of CPU, amount of RAM and HDD used. CPU cores are not limited.
