### ISSUE TITLE
Check MariaDB template

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2183]
We have an issue regarding logging in with MariaDB in container created from our MariadDB template:
```
Neil Spink [1:11 PM] 
I was also wondering about the MariaDb template. The login from command line was not possible. Usually it would have the auth plugin, so you would not be prompted. Is there any mandatory documentation on templates?
```

**Comment by neilspink** [comment]
SSH in and in the terminal I wanted to use the command -> mysql -u root <- but it asks for a password. Normally MariaDB is using the auth plugin, so if running as root you would be presented directly with the database prompt. I just figured out the password was root.

**Comment by neilspink** [comment]
**I was looking for documentation and that was my question.** It would help if templates had notes somewhere, like a readme file or on the hub.

**Comment by Dilshat** [comment]
MariaDB template was deprecated in favor of blueprints based workflows
