### ISSUE TITLE
Get Token REST API not responding correct status code

### ISSUE THREAD

**Issue by jadilet** [subutai-io/peer-os#2232]
How reproduce:

*Method:* Post
*URL:* https://$IP:8443/rest/v1/identity/gettoken
*1. attempt credentials*
`username: correct`
`password: incorrect`
`Response: 500 server error`

*2. attempt credentials*
`username: incorrect`
`password: correct`
`Response: 200 OK`

*3. attempt credentials*
`username: incorrect`
`password: incorrect`
`Response: 200 OK`

Solution: if credentials correct so the server should return 200 status code.
if credentials both incorrect so the server should return 401 status code.

**Comment by amol4anoff** [comment]
Done.

**Comment by amol4anoff** [comment]
Checked with Adilet, works
