### ISSUE TITLE
Increase timeout for management update check command

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2265]
Current timeout of 30 sec is not enough sometimes to check for new management update availability

**Comment by akarasulu** [comment]
A static simple timeout never works. This is why a decaying timeout series is used for retries. For example you try and it times out, and retries again after say 15, 30, 60, 120 etc.  Might want to consider using this kind of scheme where retries are concerns in general and where we do not retry but have some time out that is not working well.

**Comment by Dilshat** [comment]
This is agent run command that calls apt-get update or snap refresh
So we may just put big timeout like 30 minutes instead of retrying

**Comment by akarasulu** [comment]
Was more a general comment. Might not apply to this case but just wanted to mention it.

**Comment by amol4anoff** [comment]
I checked, it checks for update for about 5 seconds. If there's update, it takes about 20 seconds.

**Comment by amol4anoff** [comment]
ok, skip. Its in code.
