### ISSUE TITLE
Enable clients to obtain environment reference to be able to track progress

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2273]
Similar to how Console creates environment showing progress to user:
![image](https://user-images.githubusercontent.com/3367326/36424053-48dc6c52-166c-11e8-8766-57459245a1d3.png)

we need to enable clients (like Vagrant plugin) to be able to track the environment creation progress.
For this we need to add support to client REST API

**Comment by amol4anoff** [comment]
Will be able to test it after vagrant plugin release
