### ISSUE TITLE
Integrate RH update into Console update

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2282]
RH update can be checked/performed via Console using `subutai update rh & disown` command.
We can integrate this into Console update mechanism to enable peer owner keep their peers fully up-to-date

**Comment by amol4anoff** [comment]
It works, tested it

**Comment by Dilshat** [comment]
Now update via Console UI also performs RH update

**Comment by amol4anoff** [comment]
Before update:
snap list
Name            Version       Rev   Developer  Notes
core            16-2.31.1     4110  canonical  core
subutai-master  6.2.1-master  185   ssf        devmode

After:
snap list
Name            Version                   Rev   Developer  Notes
core            16-2.31.1                 4110  canonical  core
subutai-master  6.2.1-25-gb3d24c0-master  194   ssf        devmode
