### ISSUE TITLE
Network issue on newly created container hosts

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/peer-os#2308]
Network issue on newly created container hosts, when container host newly create there is warmup and during this period there is issue with internet connection. This problem can be seen during BP env. creation. Sometimes it can't pull files from GitHub.

**Comment by akarasulu** [comment]
What about a decaying timeout?

**Comment by zubaidullo** [comment]
What I'm thinking now is to check network connection and retry pulling data multiple times (it will take some time, but it's better than fail)

**Comment by Dilshat** [comment]
This is a network warmup that should be handled by app

**Comment by zubaidullo** [comment]
yes, it's already handled
