### ISSUE TITLE
Optimize remote-desktop related host commands

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/peer-os#2340]
Optimize remote-desktop related host commands, currently all remote-desktop related commands are run with process and run periodically. Need to optimize, save last activity and run if last activity was not success

**Comment by amol4anoff** [comment]
I created environment with mate2go BP, waited for about half an hour, but desktop icon and ability to remote desktop in CC didn't appear -https://masterbazaar.subutai.io/users/278/environments/11847

@zubaidullo @Dilshat

**Comment by zubaidullo** [comment]
@amol4anoff are you sure, you BP is fully installed?

**Comment by amol4anoff** [comment]
This one - Fixed. Tested in master.
