### ISSUE TITLE
Peer console credentials change

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/peer-os#2346]
Please have a look at master peers, some of them change password. Reproduce - use some peers from master -  https://masterbazaar.subutai.io/peers/1769
or https://masterbazaar.subutai.io/peers/1773
Then access it via console in bazaar, or open it's console directly. Login there with standard credentials we use, you will find that password is wrong, although nobody changed it.

**Comment by Dilshat** [comment]
This was due to this bug
