### ISSUE TITLE
Not clear how to add RH to peer in Subutai Console

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/peer-os#2377]
This documentation is not clear - https://github.com/subutai-attic/subos/wiki/How-to-install-several-peers-within-the-same-LAN
Me and Alina tried this: logged in in Subutai Console, then unregistered another peer from Bazaar, then we moved to "resource host" section in subutai console. Then that unregistered peer appeared in this section, but when we add it there, it becomes offline, then we remove it to add again, but after this, it is not visible anymore and we do not see any button to search for it.
Can that process in documentation be described in more detailed way, so we can easily handle and test it properly, please?

**Comment by Dilshat** [comment]
That doco is archived, use this one
https://github.com/subutai-io/snap/wiki/How-to-install-several-peers-within-the-same-LAN
