### ISSUE TITLE
In Console information about deleted environments doesn't delete

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/peer-os#2399]
In console I can see deleted environments with unknown state, but on bazaar this environments destroyed.
How to reproduce:
1. Start to build any BP on bazaar.
2. don't wait for finish of building
3. Destroy environment
Result: Environment deleted from bazaar, but still exists in Console. 
https://bazaar.subutai.io/peers/4792
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/323deebb-ffaf-42cd-ac9f-2aeac50cc788)

**Comment by Dilshat** [comment]
Console deletes only those Hub environments that are returned by REST `/rest/v1/adapter/peer/deleted/environments`

This is result from this call:
```
5078e54c-eee6-49d3-99a7-2b209e7c814d, 
d66dfc41-51eb-41f9-a5ec-97518108dfd2, 
0db11d36-d610-4cc7-aef7-c8558937cdff,
3d7dad29-c2f8-4c9c-bf7d-74fe5a4e826b, 
066623d0-caa9-411d-9d3d-92be6027f377, 
824b4a98-d127-4255-902c-6cd5b5b9d7cb
```
and these are the environments that are not deleted in Console:
![image](https://user-images.githubusercontent.com/3367326/38657950-b0110626-3e44-11e8-9c96-928234cc0c8c.png)

**Comment by Dilshat** [comment]
@AlinaPenkina @absidish as you see the IDs are not supplied by Bazaar and therefore the env-s are not deleted

**Comment by Dilshat** [comment]
@AlinaPenkina since there was not reaction from you and @absidish I am closing this issue for now
