### ISSUE TITLE
Crossing Firewall Blocks on the Installation?

### ISSUE THREAD

**Issue by marlluslustosa** [subutai-io/peer-os#2435]
Is there any option for the PeerOS to work with socks, ssh tunnel, or another solution to overcome firewall blockages in computer networks?

I have access to a server that has all ports freed, so I was thinking of connecting to it by ssh tunnel, however, I do not know how I would change the parameters on the installation itself to specify local->remote ports.

Another option would be for PeerOS to work with socks and have some configuration for this.

Can someone help me?

**Comment by marlluslustosa** [comment]
Hello, this is already a help, because I can map the p2p ports to know which ones I will use.

However, I wanted something more geared towards tunneling all connections via ssh tunnel or socks to be able to pass through a firewall block (global drop policy).

Is there something like this?

I thought of a script to tunnel all the connections of the subutai to a server elsewhere (this with global accept policy), or even redirect the traffic of these specific ports and thus be able to go through the block, but, I still do not understand the structure of connections of the subutai.

**Comment by crioto** [comment]
No, there is no support for any kind of proxies/tunnels as for now. 

Subutai P2P works like most of the other P2P applications and use the same techniques to bypass NAT and firewalls (e.g. like Skype or torrent clients) - if your firewall allows outgoing traffic P2P will connect (we are using internal proxies to pass traffic when direct connection is impossible)

**Comment by marlluslustosa** [comment]
(udp/53, udp/67, tcp/80, tcp/443, udp/1900, udp/6881, tcp/8086, tcp/8444/8443 - https://docs.subutai.io/Products/PeerOS/02_Install_PeerOS .html

I wanted to know which ports I should releasing except that the documentation quotes. Because as I talked about this in another topic (https://github.com/subutai-io/agent/issues/484), I released the ports for output on the firewall and still could not make the subutai agent work (the possible cause is the "random" udp ports it tries to connect to).

**Comment by marlluslustosa** [comment]
@Dilshat the error refers to unsuccessful attempts to connect to udp ports.

When it tries to connect to one port and it does not work, it goes to another port, and so it tests the ports indefinitely. Even though the doors that the tutorial asks for have been released.

**Comment by Dilshat** [comment]
@marlluslustosa if you see errors that contain ssdp .. udp then this should be fixed with the latest release.
Please update your peer and check again

**Comment by marlluslustosa** [comment]
@Dilshat If I'm not mistaken, had ssdp udp error.
I'll try to reinstall and see what happens!

Thank you
