### ISSUE TITLE
In Subutai Console, "updates available" makes no sense

### ISSUE THREAD

**Issue by niclash** [subutai-io/peer-os#2487]
The "Bell" icon in upper right corner on the Subutai Console, says "Updates Available" and a time stamp of the Resource Host's update time, and a button to a page that is empty list.

It doesn't make sense.

**Comment by niclash** [comment]
![screen shot 2018-06-07 at 12 36 37](https://user-images.githubusercontent.com/106693/41078474-9781e774-6a4f-11e8-8f7a-31fab3f830fc.png)
![screen shot 2018-06-07 at 12 36 55](https://user-images.githubusercontent.com/106693/41078477-9dd15df8-6a4f-11e8-9ef0-bcde0a58caa6.png)
![screen shot 2018-06-07 at 12 37 05](https://user-images.githubusercontent.com/106693/41078480-a0daafcc-6a4f-11e8-9229-1384dd739e32.png)

**Comment by Dilshat** [comment]
Yeah we can remove that button from Notifications

**Comment by AlinaPenkina** [comment]
Fixed.
