### ISSUE TITLE
Add `shared` as a value in addition to `private` and `public` in the form attribute `peerScope` while registering peer to bazaar

### ISSUE THREAD

**Issue by jadilet** [subutai-io/peer-os#2502]

**Comment by zubaidullo** [comment]
@jadilet why you need Shared scope?
From management console it's impossible to make peer shared. To use shared scope, you should choose user, with whom you will share. So, in MC there is no user info, peer will have only Private, Public scopes

**Comment by jadilet** [comment]
@zubaidullo  Is it possible to implement this feature? If we provide user's email which we're sharing peer with him.

**Comment by etursunbaev** [comment]
@zubaidullo but via bazaar when you change scope to shared it does not require select users mandatory. 
You select users when you changed already. So I assume it is possible to provide such feature.

**Comment by zubaidullo** [comment]
yes, this is possible from Bazaar for sure, but I don't seen any reason to make peer shared w/o sharing with someone

**Comment by zubaidullo** [comment]
> @zubaidullo Is it possible to implement this feature? If we provide user's email which we're sharing peer with him.
yes, but need to add this feature in MConsole

**Comment by Dilshat** [comment]
Seems this is to simplify UX, User will just need to share with user in Bazaar without having to change peer scope too

**Comment by etursunbaev** [comment]
I think it is related to registration part. When registration done owner can choose users with whom to share via bazaar

**Comment by AlinaPenkina** [comment]
Fixed.
