### ISSUE TITLE
Pull template logos from CDN

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/peer-os#2515]

**Comment by zubaidullo** [comment]
This is more related to front-end side. Logos are checked in UI if exists or not. Seems, during this proccess b/c of speed it can't load sometimes

**Comment by kurmanbekova6** [comment]
![image 1](https://user-images.githubusercontent.com/9501291/41778184-b616f6c8-764f-11e8-8341-accd8bfa6cb9.png)

**Comment by Dilshat** [comment]
blocked by https://github.com/optdyn/hub/issues/6122

**Comment by Dilshat** [comment]
How to test:
1) Go to Environment->Environments section and view templates icons
Result: the templates that have icons uploaded by owners to Bazaar CDN must have icons on Console UI too

**Comment by kurmanbekova6** [comment]
Followed the steps described above:
Uploaded logo
Checked from bazaar and console side.
![screenshot_1](https://user-images.githubusercontent.com/9501291/48768865-13a67080-ec6f-11e8-9d2d-ca18a03fe169.png)
![screenshot_2](https://user-images.githubusercontent.com/9501291/48768870-15703400-ec6f-11e8-8d23-ccf8d8540151.png)
![screenshot_3](https://user-images.githubusercontent.com/9501291/48768875-186b2480-ec6f-11e8-97f9-68056550b187.png)
![screenshot_4](https://user-images.githubusercontent.com/9501291/48768878-199c5180-ec6f-11e8-95ad-2971968c9ee6.png)
Tested in master
