### ISSUE TITLE
Environment state is unhealthy while building environment via REST API 

### ISSUE THREAD

**Issue by jadilet** [subutai-io/peer-os#2518]
Vagrant Subutai plugin uses following REST API to build environment:
URL: `/rest/v1/environments?sptoken=`
Template name: `debian-stretch`.

Karaf logs:
[karaflogs2018-06-23 18_39_28.txt](https://github.com/subutai-io/peer-os/files/2129903/karaflogs2018-06-23.18_39_28.txt)

**Comment by Dilshat** [comment]
@jadilet please write peer branch

**Comment by Dilshat** [comment]
@jadilet  Seems you passed wrong template id
```
Template `5323235b-51a7-43b8-a8d4-e0abbad9921a` not found
```

**Comment by jadilet** [comment]
Peer branch is `master`. I'm getting `template id` from cdn by template name. Should I  only provide `template name` ?

**Comment by Dilshat** [comment]
Are you using new cdn on bazaar.subutai.io?

**Comment by Dilshat** [comment]
@jadilet

**Comment by Dilshat** [comment]
reason found
