### ISSUE TITLE
Peer can't send version info to bazaar

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/peer-os#2543]
_moving here from optdyn/hub#4554_

First of all I need to say that this happens rare and to several peers only (as I noticed it happens only to Lars's peers which have public IP). Previously it happened to other peers (see comments in hub issue), but after some period of time (2-3 weeks passed) those peers are recovered and now able to send versions (for example this peer was having that issue and now is ok: https://bazaar.subutai.io/peers/5606). On other peer we couldn't figure out the cause, and reimported management, and it also worked after that.

So, at the moment only this peer having this issue:
![image](https://user-images.githubusercontent.com/4163679/42493397-b18de9e8-843e-11e8-9d80-cb361c421b66.png)

In bazaar it shows old version because peer didn't send version info. In Subutai Console peer is up to date:
![image](https://user-images.githubusercontent.com/4163679/42493445-e10028ee-843e-11e8-810d-7c60ba0de9e8.png)

In peer karaf logs we see that it fails to send version info because of timeout, but other requests works ok(like heartbeat):
```
2018-07-10 06:41:07,001 | ERROR | pool-42-thread-9 | HubRestClient                    | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | Error executing request to Hub: java.net.SocketTimeoutException: SocketTimeoutException invoking https://masterbazaar.subutai.io:444/rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/version-info: Read timed out
2018-07-10 06:43:08,053 | ERROR | pool-42-thread-4 | HubRestClient                    | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | Error executing request to Hub: java.net.SocketTimeoutException: SocketTimeoutException invoking https://masterbazaar.subutai.io:444/rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/version-info: Read timed out


2018-07-10 06:42:50,928 | INFO  | pool-43-thread-1 | HeartbeatProcessor               | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | Sending heartbeat to HUB: interval=60, force=false, fastModeLeft=-812
2018-07-10 06:42:50,928 | INFO  | pool-43-thread-1 | HeartbeatProcessor               | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | Heartbeat - START
2018-07-10 06:42:50,928 | INFO  | pool-43-thread-1 | HubRestClient                    | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | POST /rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/heartbeat/6378442
2018-07-10 06:42:51,264 | DEBUG | 948776017-229809 | AuthorizationInterceptor         | 3 - io.subutai.core.blueprint.auth - 7.0.5.SNAPSHOT | Granting access to Method: public javax.ws.rs.core.Response io.subutai.core.executor.rest.RestServiceImpl.check(java.lang.String) for RolePrincipal[Resource-Management|Read].
2018-07-10 06:42:51,737 | INFO  | pool-43-thread-1 | HubRestClient                    | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | response.status: 200 - OK
2018-07-10 06:42:51,740 | INFO  | pool-43-thread-1 | HeartbeatProcessor               | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | stateLinks: []
2018-07-10 06:42:51,740 | INFO  | pool-43-thread-1 | HeartbeatProcessor               | 223 - io.subutai.core.hubmanager.impl - 7.0.5.SNAPSHOT | Heartbeat - END
```

attaching karaf.logs just in case: [karaflogs2018-07-10 12_51_09.txt](https://github.com/subutai-io/peer-os/files/2179182/karaflogs2018-07-10.12_51_09.txt)

Version info request is not reaching Bazaar application, it's reaching bazaar Nginx, but it shows that zero data is sent (see zero after 408 in Nginx logs below):
```
62.138.0.36 - - [10/Jul/2018:06:49:10 +0000] "POST /rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/version-info HTTP/1.1" 408 0 "-" "Apache CXF 3.1.0"
62.138.0.36 - - [10/Jul/2018:06:50:10 +0000] "POST /rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/version-info HTTP/1.1" 408 0 "-" "Apache CXF 3.1.0"
62.138.0.36 - - [10/Jul/2018:06:52:11 +0000] "POST /rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/version-info HTTP/1.1" 408 0 "-" "Apache CXF 3.1.0"
```

At the same time if I send request to that endpoint from RH CLI or from inside `management` container CLI of that peer, request is reaching bazaar application and handled by it:
![image](https://user-images.githubusercontent.com/4163679/42494974-91df6c52-8443-11e8-9007-5eb9e19f70ec.png)

So, request fails only when it's sent from inside Subutai Console application itself.

**Comment by Dilshat** [comment]
I debugged the Console on the specified peer https://masterbazaar.subutai.io/peers/2993#
First besides the error mentioned above I also got :
![image](https://user-images.githubusercontent.com/3367326/42501758-3c25b75e-8456-11e8-9b56-32b6fb0f12df.png)

```
javax.ws.rs.ProcessingException: java.net.SocketException: SocketException invoking https://masterbazaar.subutai.io:444/rest/v1/peers/7EB3E3974A9F27B97F1DC99A93B5AF2973CAB446/version-info: Unexpected end of file from server
```

from Console side the body was not empty and request was properly sent to Bazaar:
![image](https://user-images.githubusercontent.com/3367326/42501868-6f794832-8456-11e8-9eb0-ab937df6291c.png)

I serialized the body to a file 
[post](https://github.com/subutai-io/peer-os/files/2179735/version-info.txt)

and tried from inside of the peer's management container and got this:

![image](https://user-images.githubusercontent.com/3367326/42501745-33d311dc-8456-11e8-98a5-28ffacaae2ea.png)

So this is definitely not a Console issue, but can be related to peer network or Bazaar side
@samsonbek @lbthomsen

**Comment by lbthomsen** [comment]
One thing that is important to stress - on "master" I have five peers all managed in exactly the same way with ansible.  All these five have public IP and they are for all intends and purposes identical - same os, same software installed, installed around the same time, all running on public IP's etc. etc.

**Comment by lbthomsen** [comment]
You should all have access to the peer if needed - eu2.s.optdyn.com

**Comment by niclash** [comment]
@Dilshat Could you please also do the same operations on one of the other 4 servers, just to validate that your approach is expected to work?

**Comment by Dilshat** [comment]
I repeated the experiment on master-peer-us-2 (148.72.176.38) and it returned correct error since fingeprint is missing in the request:
```
master-peer-us-2:~# curl --request POST --data-binary "@post" https://masterbazaar.subutai.io:444/rest/v1/peers/74F1854507B4D774F3EDA30F998477024A661A2E/version-info
Cannot get the fingerprint from the requestmaster-peer-us-2:~#
```
you can see the difference comparing it with the response above
@niclash

**Comment by samsonbek** [comment]
Bazaar handles all peers the same way, so if it works for other peer, it must work for this peer too. Unless this peer is not some specific issues.

**Comment by Dilshat** [comment]
This is certainky something with networkilg on Bzr side, probably nginx or other stuff

**Comment by Dilshat** [comment]
Recently this issue has not appeared

**Comment by Shahrizada** [comment]
faced this issue on https://bazaar.subutai.io/peers/7195#

![screen shot 2018-08-29 at 11 21 29](https://user-images.githubusercontent.com/31571523/44767139-6dbafc80-ab7e-11e8-90d6-4ae5ef84c9b7.png)
![screen shot 2018-08-29 at 11 21 22](https://user-images.githubusercontent.com/31571523/44767144-73b0dd80-ab7e-11e8-94f0-303c94cd2676.png)

some conversations on Slack:
![screen shot 2018-08-29 at 11 27 53](https://user-images.githubusercontent.com/31571523/44767184-a4911280-ab7e-11e8-8e87-b495f0964c76.png)

**Comment by etursunbaev** [comment]
It is network issue in MH
To investigate this issue I wanted to install some net tools but could not, installation always hung and failed  on every peer where this issue was.
```Err:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libpcap0.8 amd64 1.8.1-3
  Connection failed [IP: 151.101.84.204 80]
Get:2 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 tcpdump amd64 4.9.2-1~deb9u1 [415 kB]
Fetched 415 kB in 6min 2s (1144 B/s)
E: Failed to fetch http://cdn-fastly.deb.debian.org/debian/pool/main/libp/libpcap/libpcap0.8_1.8.1-3_amd64.deb  Connection failed [IP: 151.101.84.204 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
So it was something wrong with network. 
I noticed that MH eth0 MTU is 1500 
```
106: eth0@if107: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:ed:d2:97 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.10.10.1/24 brd 10.10.10.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::216:3eff:feed:d297/64 scope link 
       valid_lft forever preferred_lft forever
root@management:/# nano /etc/network/interfaces
```
and compared with other working fine peer, it differed. In working fine peers the MTU value was 1450
So, I changed on 3 peers MH eth0 MTU value to `1450` and restarted network
Than it worked, these 3 peers version info in Bazaar got right version.

I don't know how and when it got 1500 MTU, maybe it was for a long time. 
So it should be changed perhaps on next updates?!

**Comment by Dilshat** [comment]
fixed
