### ISSUE TITLE
Check if p2p status sending works correctly

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2579]
Check if p2p status is sent regularly to Bazaar

**Comment by Dilshat** [comment]
The logic will be as follows:
1. Console sends p2p statuses of RHs to Bazaar every hour
2. In case any RH has non zero exit code from ```p2p status``` command, Console will send more frequently (once in 10 minutes) until the issue resolves.
3. P2PDto.p2pStatus field will hold exit code of ```p2p status``` command.

**Comment by akarasulu** [comment]
@Dilshat this functionality was there already if I remember correctly. Was this a regression where it broke?

**Comment by Dilshat** [comment]
status sending was there but it didnt accommodate case where p2p service might be down

**Comment by AlinaPenkina** [comment]
Fixed in master.
