### ISSUE TITLE
Console UI should allow container names that meet ARPANET hostname requirements only

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2588]
The labels must follow the rules for ARPANET host names.  They must
    start with a letter, end with a letter or digit, and have as interior
    characters only letters, digits, and hyphen.  There are also some
    restrictions on the length.  Labels must be 63 characters or less.

**Comment by Dilshat** [comment]
Console will limit container names to 50 symbols to reserve 13 symbols for mandatory suffix automatically appended by peer

**Comment by AlinaPenkina** [comment]
Fixed in master.
