### ISSUE TITLE
Host selector does not work on Monitoring page

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2600]
Host selector does not work 

![image](https://user-images.githubusercontent.com/3367326/43635610-6dfe7ade-9731-11e8-9eb9-9c7a30664160.png)

**Comment by mattcollier** [comment]
I'm looking at v7.0.6 so I know this patch has not been released yet.  Just to make sure this is the same issue that I'm seeing.

I go to monitoring, from the Peer tab, I select a host, and the data is displayed as expected.  Then I switch to the management tab, the data is displayed as expected.  Then I switch back to the Peer tab, select a host again and nothing happens, the graphs from the management tabs is still displayed.

**Comment by Dilshat** [comment]
@mattcollier yes , the patch has not been released yet, it is the same issue

**Comment by Dilshat** [comment]
How to test:

Setup a peer with a second RH.
On monitoring page try to change the peer selection.
It should change showing separate monitoring metrics for each RH

**Comment by AlinaPenkina** [comment]
1. Created peer with 2 RH's
2. In monitoring page switching between 2 Rh's
Monitoring graphics are different:
![image](https://user-images.githubusercontent.com/34295807/44458699-d65b2400-a628-11e8-940f-9cfed5bc84c9.png)

**Comment by AlinaPenkina** [comment]
Done.
