### ISSUE TITLE
User can't register peer by using his username

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/peer-os#2602]
Here is written login, but I tried with login and it can't register. we can use only e-mail.
Please change this "login" word to "email", or add function to register peer by username:
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/e96994bd-1a91-433a-a260-ae139fbcc1aa)

**Comment by Dilshat** [comment]
Blocked by https://github.com/optdyn/hub/issues/6873

**Comment by Dilshat** [comment]
How to test:

Enter username rather than email and try to register peer with BZR.
Peer should get registered successfully

**Comment by AlinaPenkina** [comment]
![image](https://user-images.githubusercontent.com/34295807/44336479-64a0a000-a499-11e8-90ce-2f0b06c53cb0.png)

**Comment by AlinaPenkina** [comment]
Fixed.
