### ISSUE TITLE
[x-peer] Failure to obtain metrics of remote environment containers

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2634]
When trying to view metrics of remote containers (of x-peer environment) , 500 error is returned

![image](https://user-images.githubusercontent.com/3367326/44984082-51172e00-af9d-11e8-9330-063578e9d1cc.png)

**Comment by Dilshat** [comment]
Remote environments should be hidden on Monitoring page

**Comment by Dilshat** [comment]
How to test:

Create x-peer environment
View metrics of remove container on initiator peer

**Comment by kurmanbekova6** [comment]
Did not get any errors. Fixed in Master
![screenshot_14](https://user-images.githubusercontent.com/9501291/45861466-8342d100-bd8e-11e8-8d48-0a5a11fc5318.png)

**Comment by kurmanbekova6** [comment]
![screenshot_15](https://user-images.githubusercontent.com/9501291/45861509-c00ec800-bd8e-11e8-845f-3ce81839e398.png)
