### ISSUE TITLE
[x-peer] Can not set hostname of remote container

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2635]
Setting hostname of remote container (x-peer environment) is not available:

![image](https://user-images.githubusercontent.com/3367326/44984146-8cb1f800-af9d-11e8-84dd-f10c60e3d42f.png)

**Comment by Dilshat** [comment]
How to test:

Create x-peer environment
Set hostname of container on remote peer via initiator peer

**Comment by kurmanbekova6** [comment]
Followed by test case. Fixed in Master
![screenshot_16](https://user-images.githubusercontent.com/9501291/45862171-5395c800-bd92-11e8-9080-61f3117a68bb.png)
