### ISSUE TITLE
Add check if RH can provide the requested resources

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2642]
As a part of [Resource management epic](https://github.com/subutai-io/peer-os/issues/2603)
implement checking if RH can provide enough resources to accommodate the requested amount of resources during new environment creation or existing environment modification process

**Comment by Dilshat** [comment]
How to test:
Inside management container, edit file `/opt/subutai-mng/bin/setenv`
set/add property `CHECK_RH_LIMITS=true`
restart console `service management restart`

Create console environment with containers that together exceed resources available in peer
Console should show error message

**Comment by kurmanbekova6** [comment]
![screenshot_17](https://user-images.githubusercontent.com/9501291/45863318-7b3b5f00-bd97-11e8-9872-34b285cf12a0.png)
![screenshot_18](https://user-images.githubusercontent.com/9501291/45863323-82626d00-bd97-11e8-99e9-2fc969f65cab.png)
Fixed in Master
