### ISSUE TITLE
Dont show own templates category in environment page

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2667]
To avoid having user enter pgp key password in **Environments** page, we need to remove showing `Own` templates group since templates owners are shown in `All` templates group when hovering mouse over them.
Also we need to make e2e plugin to ask pwd on **Containers** page only when a container is attempted to be exported to a template. Currently it asks it when opening the page.

**Comment by zubaidullo** [comment]
duplicate #2666
