### ISSUE TITLE
Permissiond denied on cert.pem

### ISSUE THREAD

**Issue by efeefe** [subutai-io/peer-os#2670]
I'm getting this error when I ssh into my local peer (via vagrant) and try to run any subutai command:

FATA[2018-10-01 21:33:53] Generating PEM certificate, open /var/lib/subutai/ssl/cert.pem: permission denied

Apparently, the file is there and the subutai user belongs to the "root" group:

sudo ls -lah /var/lib/subutai/ssl/cert.pem
-rw-r--r-- 1 root root 1.1K Sep 21 11:27 /var/lib/subutai/ssl/cert.pem

groups subutai
subutai : subutai root cdrom floppy sudo audio dip video plugdev netdev

This peer was installed via Vagrant with Control Center some weeks ago and has been updated regularly.

**Comment by Dilshat** [comment]
commands were run under `subutai` user whereas we need to run them under `root`
