### ISSUE TITLE
PeerOs not responding exact error message on unregister peer REST API

### ISSUE THREAD

**Issue by jadilet** [subutai-io/peer-os#2673]
CC uses following PeerOs `REST API` for unregistering the peer.
I have peer registered to the bazaar. My peer has the environment on the bazaar.

## REST API
`/rest/v1/hub/unregister?sptoken=`

## Current Behavior
PeerOS not responding exact error message if The peer has environment on the bazaar.
Just send response: `Internal server error`

![image](https://user-images.githubusercontent.com/6593519/46405516-4c73a000-c72a-11e8-9d90-2f4bafadd375.png)

When I try to unregister via peer os UI, it gives the exact error message.

![image](https://user-images.githubusercontent.com/6593519/46405601-9066a500-c72a-11e8-9306-8a6db616b4e1.png)

## Expected Behavior
PeerOS should response exact error message. (This peer has environments on Bazaar. Please remove environments first to unregister peer.)

**Comment by Dilshat** [comment]
Response body contains the error description
![image](https://user-images.githubusercontent.com/3367326/46453194-fb16ef80-c7c1-11e8-8e37-8458aafe1fa1.png)

**Comment by jadilet** [comment]
Now PeerOS response exact error message:

![image](https://user-images.githubusercontent.com/6593519/46472575-7a76e400-c7ff-11e8-81a7-8d33a3b756fc.png)
