### ISSUE TITLE
We need to set peer scope private by default on Bazaar registration

### ISSUE THREAD

**Issue by absidish** [subutai-io/peer-os#2677]
we need to make peer scope **private** by default on the register to Bazaar also we need details for each scope.

**Comment by Shahrizada** [comment]
Imho, nothing should be set by default. We need to leave the scope empty and forse user to choose the scope. Of course, the explanation of the scopes needs to be there as well.

**Comment by Dilshat** [comment]
![image](https://user-images.githubusercontent.com/3367326/46594681-7811d400-caf6-11e8-9b1e-5ff67aca5bba.png)
