### ISSUE TITLE
Synchronization of p2p environments between Bazaar and Peer

### ISSUE THREAD

**Issue by crioto** [subutai-io/peer-os#2686]
p2p is not aware about what environments it should run on startup. For this reason p2p uses so called `p2p.save` file, which is basically a dump of previously created environments. In a situation, when this file get damaged/missing/wiped p2p will not run this environment anymore and this is the problem. My suggestion is to periodically run checks of existing p2p connections (these checks must be initiated by Subutai) and compare them to the list of known environments. In the case when environment is missing in p2p, but exists in Subutai - Subutai must recreate this environment. 
Also, Subutai can add this information (list of envs) to the heartbeat and send then to Bazaar and then, Bazaar may initiate recreation of p2p environment. This is another way to solve this. We need to discuss which way is better.

**Comment by Dilshat** [comment]
Simplest way is to backup this file

**Comment by Dilshat** [comment]
Handled by https://github.com/subutai-io/p2p/issues/1106
