### ISSUE TITLE
Peer registration failed in MacOS

### ISSUE THREAD

**Issue by etursunbaev** [subutai-io/peer-os#2687]
It is rare issue, but happened several times and not on all Mac.
![screen shot 2018-10-24 at 1 52 34 pm](https://user-images.githubusercontent.com/33412152/47428599-90037c00-d7b5-11e8-9135-d4426902f51c.png)

Nginx responded with 400 code error.
And we noticed that time differs
```Abdysamat Mamutov [2 hours ago]
hmm, according to bazaar nginx logs, request happened at 09:57:50


Abdysamat Mamutov [2 hours ago]
but karaf log ends with 22:55:29,442
```

We could register after changing TZ on Mac. It was US tz and restarted console, after that were able to register peer.

But could not reproduce again.

Need to reproduce

On Mac change TZ than build peer. Register peer, if it fails set right TZ UTC and restart peer than try again to register
After succesfull registration - unregister and change to different TZ, restart peer and try to register peer

**Comment by Dilshat** [comment]
closed until reproduced
