### ISSUE TITLE
Add support for LetsEncrypt certificates

### ISSUE THREAD

**Issue by tjamakeev** [subutai-io/peer-os#2707]
We need to integrate Let's Encrypt SSL on `https` port mapping

**Comment by Dilshat** [comment]
How to test:
1) Create env via Bazaar with container from nginx/apache template
2) Add domain with LE certificate to the container
3) Open domain
Result: domain must open and show nginx/apache welcome page and green word `Secure` on the left of the url in browser

**Comment by kurmanbekova6** [comment]
![screenshot_14](https://user-images.githubusercontent.com/9501291/48839565-bc70d080-ed40-11e8-877c-d30b26d0b770.png)
![screenshot_15](https://user-images.githubusercontent.com/9501291/48839571-bed32a80-ed40-11e8-837c-f53614548a2c.png)
Tested in master
