### ISSUE TITLE
Container destruction via agent CLI is not immediately reflected on UI

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/peer-os#2718]
How to reproduce:
- create environment with 1 container either from Bazaar UI or from Subutai Console UI
- go to RH CLI and destroy that container with command `subutai destroy <container name>`
- open this environment in Bazaar and try to add SSH key to it
Result: operation will end up with following error:
![image](https://user-images.githubusercontent.com/4163679/48389324-2bd63700-e727-11e8-9181-7fbcaf00969a.png)

See optdyn/hub#6477 for more details.

Expected behavior: when container is destroyed via CLI, management should detect it instantly and reflect on UI and send this info to bazaar.

**Comment by Dilshat** [comment]
will be handled by https://github.com/subutai-io/agent/issues/849
