### ISSUE TITLE
Prohibit registering RH if it has containers from other peer

### ISSUE THREAD

**Issue by maksimyugai** [subutai-io/peer-os#2727]
Don't allow to register secondary RH if it has containers created by BZR. And it should be configurable from the config file. if it's not clean. 

https://optdyn.slack.com/archives/C6X2EH7DE/p1542364951298000

**Comment by Dilshat** [comment]
How to test:
Try to register with a secondary RH that has container of its peer to another peer.
Result: registration must not be allowed

**Comment by kurmanbekova6** [comment]
Created peer. Created environment on it. Then destroyed management.  From first peer's RH sent registration request to the second peer.
Result: 


![screenshot_26](https://user-images.githubusercontent.com/9501291/50067830-038d9c80-01ed-11e9-8497-d932188f4622.png)
Tested in master.
