### ISSUE TITLE
TCP port mapping on ports used for ssh goes wrong

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/peer-os#2740]
TCP port mappings using the ports used for ssh mapping can go wrong.

**Comment by lbthomsen** [comment]
Steps to reproduce:

1. Create 1 env with 1 container running on nat'ed peer:

2. Create port mappings

![image](https://user-images.githubusercontent.com/2730860/49322677-8acfe480-f54c-11e8-9775-6c59d9b5e807.png)

`ssh -p 10004 root@lars123.envs.subut.ai` is working
`ssh -p 10003 root@lars123.envs.subut.ai` is not working

**Comment by lbthomsen** [comment]
This may be relevant: 

![image](https://user-images.githubusercontent.com/2730860/49322718-f2862f80-f54c-11e8-88c7-9180944db45b.png)

**Comment by lbthomsen** [comment]
And yes - this is obvious!!!!  Two scenarios:

1. Peer with public IP

No problems at all

2. Peer behind nat

Port mappings need to be made on a proxy peer.  Connection FROM proxy peer TO peer goes through the same p2p mechanism as SSH connections from client and so get caught by the same rule that is used for ssh.

Consider this port mappng:

![image](https://user-images.githubusercontent.com/2730860/49334408-3f7f0a00-f610-11e8-8792-20946ab27eae.png)

Everything works except the last one (container-7 is using port 10008 for ssh)

**Comment by lbthomsen** [comment]
The final (10008) one goes: ```lth@ncpws04:~$ telnet p1.envs.subut.ai 10008
Trying 62.138.16.147...
Connected to p1.envs.subut.ai.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3```

**Comment by lbthomsen** [comment]
https://github.com/optdyn/hub/issues/7754

**Comment by Dilshat** [comment]
will be handled by optdyn/hub#7754
