### ISSUE TITLE
Fix duplicate IP address assignment

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/peer-os#2749]
Steps to reproduce:
    Create peer.
    Add rhs.
    Turn off one of the rhs and turn on back.
    Go to Console =>Resource Hosts and approve request.

Result: On bazaar you will see one online and one offline rhs with the same ip address.
![screenshot_11](https://user-images.githubusercontent.com/9501291/49488989-f1c7f480-f7fd-11e8-92ec-eb4ada7ab7c7.png)
![screenshot_12](https://user-images.githubusercontent.com/9501291/49488995-f8566c00-f7fd-11e8-96af-c564dffc687f.png)
![1](https://user-images.githubusercontent.com/9501291/49488997-fc828980-f7fd-11e8-807f-49d4f7c3e4f8.png)
![2](https://user-images.githubusercontent.com/9501291/49489002-fe4c4d00-f7fd-11e8-9a47-df47aed648aa.png)

**Comment by Dilshat** [comment]
Follow the steps above to test this issue

**Comment by kurmanbekova6** [comment]
Followed the steps above:
After turning on rh, did not get a request on console.
Did not face with it
Tested in master
