### ISSUE TITLE
When user turns on peer via CC, management can not start

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/peer-os#2750]
**Steps to reproduce:**

Create peer.
Turn it off and turn it back on via CC.
Reload peer also did not help.
Result: 
```subutai@subutai:~$ sudo subutai list info
NAME        STATE    IP    Interface
----        -----    --    ---------
management    STOPPED        eth0```

**Comment by Dilshat** [comment]
@kurmanbekova6 with running management when you reload vagrant or reboot peer, is it the same?

**Comment by Dilshat** [comment]
WIll be handled by https://github.com/subutai-io/agent/issues/869
