### ISSUE TITLE
Fix Bazaar environment statuses

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2751]
Bazaar environments' statuses are always HEALTHY on console UI.
Need to show actual status

**Comment by Dilshat** [comment]
How to test:
1. Create Bazaar environment on a peer
2. Stop one of its containers
3. Check state of the env in Console
Result: the state must be UNHEALTHY

**Comment by kurmanbekova6** [comment]
Followed the steps described above:
Console shows correct status of bazaar's environment
![screenshot_7](https://user-images.githubusercontent.com/9501291/49984745-3a7a5e80-ff1e-11e8-82c8-fdfa4514b151.png)
![screenshot_8](https://user-images.githubusercontent.com/9501291/49984749-3bab8b80-ff1e-11e8-888b-6d199ff8adf1.png)
