### ISSUE TITLE
1 peer using two different users

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/peer-os#2764]
**Steps to reproduce:**
From user A
1. Bring peer up.
Register peer  little bit later
Result:
From resource hosts information will disappear and appear periodically
Peers
![screenshot_18](https://user-images.githubusercontent.com/9501291/50005248-851bcb00-ff5e-11e8-8515-fc7d6f079529.png)

From user B
2. From your peer go to console=> Resource hosts => Approve requests
![screenshot_8](https://user-images.githubusercontent.com/9501291/50005261-982e9b00-ff5e-11e8-83db-c337ee7b7c00.png)

Result:
Peer  will disappear and appear periodically.

**Comment by Dilshat** [comment]
Will be handled by https://github.com/optdyn/hub/issues/7681
