### ISSUE TITLE
LastPass prevents from signing in

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2771]
When LastPass is enabled, user can not sign in to Console due to LastPass filling in a hidden form field.

**Comment by Dilshat** [comment]
How to test:
1) Have LastPass remember credentials for the Console.
2) With LastPass enabled, try to login to Console
Result: Login with correct credentials must succeed

**Comment by Almansherov** [comment]
Updated a peer
Enabled LastPass and saved console credentials: 

![image](https://user-images.githubusercontent.com/32430693/50823628-05cdad00-12fa-11e9-8e68-b3b6d3a70c99.png)

Successfully got into the console.
