### ISSUE TITLE
Container hostname is not removed on container destruction

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2778]
When container is removed from environment, its hostname is left in /etc/hosts file of the other containers

**Comment by Dilshat** [comment]
How to test:
1) Create environment with more than 2 containers
2) Destroy one container via Environment->Containers section
3) Destroy one container via Environment->Environments editing pane
4) Ssh into the last container and check `/etc/hosts` file
Result: `/etc/hosts` file must not contain hostnames of the removed containers

**Comment by Almansherov** [comment]
Followed the scenario above^
However, there are still the hostnames of removed containers included inside of the last container:

![image](https://user-images.githubusercontent.com/32430693/50812124-11f44300-12d7-11e9-91b3-0e46c5967734.png)

Karaf logs from eu2 peer:

[karaflogs2019-01-07 23_52_41.txt](https://github.com/subutai-io/peer-os/files/2735330/karaflogs2019-01-07.23_52_41.txt)

Environment link: https://masterbazaar.subutai.io/users/930/environments/65915

**Comment by Almansherov** [comment]
Followed the scenario written above^
Tested with the updated peer on masterbazaar.
Did operations via console.
Successfully finished testing. `Hosts` does not have the hostnames of deleted containers:

![image](https://user-images.githubusercontent.com/32430693/50813710-e4aa9380-12dc-11e9-85a8-36d3770ae441.png)
