### ISSUE TITLE
Allow use of templates of previous versions

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2782]
Currently Console allows usage of templates of the latest versions only.
User might want to use prev versions too so need to allow this option.

**Comment by Dilshat** [comment]
Fetch all templates and order by version desc

**Comment by Dilshat** [comment]
How to test:
1. In Environments section find a template that has several versions
2. Build environment using each version of the template
Result: environment must be successfully build and result of `subutai list i -p` should show parent templates of different versions

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
Successfully built environment using debian-stretch  0.4.5, 0.4.6 from console side
From bazaar side, there no templates with different versions.

**Comment by Dilshat** [comment]
@kurmanbekova6 this is console side only for now

**Comment by kurmanbekova6** [comment]
Fixed in master
