### ISSUE TITLE
ZFS Not Mounted on hard Reboot

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/peer-os#2786]
Occasionally (trigger unknown) `subutai/fs` will fail to mount on `/var/lib/lxc` after a power cycle (clean reboot works fine) because the mountpoint `/var/lib/lxc` already exists.

It is unknown what trigger this behaviour but it is an OS level bug and should be fixed at OS level (will file upstream report if this happens repeatedly).

Detection: `mount` and check if `subutai/fs` is mounted on `/var/ilb/lxc`.  If not - move on to fix

Fix: `rmdir /var/lib/lxc && reboot` and the peer comes up fine.

**Comment by akarasulu** [comment]
Found that [this](https://github.com/akarasulu/fix-power-cycle) would make the problem go away for good.
