### ISSUE TITLE
Integrate agent's "proxy" binding into PeerOS

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/peer-os#2794]
Subutai Agent has CLI binding named [`proxy`](https://github.com/subutai-io/agent/wiki/proxy). We need to make PeerOS to use that command.

**Comment by Dilshat** [comment]
How to test:
1. Create https://domain:443 port mapping via Bazaar and select redirect option in UI
2. Navigate to http://domain (port 80)
Result: it should redirect to https://domain (port 443)

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
After navigating to http://test1.idea-x.org, domain was redirected to https
![screenshot from 2019-02-05 11-13-20](https://user-images.githubusercontent.com/9501291/52254262-155f0680-2937-11e9-8648-16dfb736ab04.png)
