### ISSUE TITLE
Replace usage of agent's "map" command with "proxy" command, for creating port mappings

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/peer-os#2795]
Subutai Agent's CLI [`map` ](https://github.com/subutai-io/agent/wiki/map) command is just a shortcut to [`proxy`](https://github.com/subutai-io/agent/wiki/proxy) command, and uses it behind the scenes. 
So, we need to replace all usages of `map` command with `proxy` command in PeerOS.

**Comment by Dilshat** [comment]
You can still use *map* command since it supports all options of proxy including `--redirect`

**Comment by samsonbek** [comment]
Ok, if so, then no need to replace `map` command.
