### ISSUE TITLE
Add new API to add ssh key to a specific user

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2797]
We need to provide method to add an ssh key to authorized keys file of a specified user inside a container

**Comment by Dilshat** [comment]
`SshKeys io.subutai.common.peer.Peer#readOrCreateSshKeysForEnvironment
`- creates ssh keys inside all containers and returns them to caller

`io.subutai.common.peer.Peer#configureSshInEnvironment( EnvironmentId environmentId, SshKeys sshKeys )`
adds specified ssh keys to all containers within environment

`io.subutai.common.peer.Peer#addToAuthorizedKeys( EnvironmentId environmentId, String sshPublicKey )
`adds a specified ssh key to all containers within environment


these methods are called by Bazaar module (or environment manager in case of local environments) during environment build

**Comment by samsonbek** [comment]
> adds specified ssh keys to all containers within environment

we need API to add ssh keys only to several chosen containers.

**Comment by Dilshat** [comment]
Check user existence `id -u {username}`
Create user with home directory `useradd -m {username}`
