### ISSUE TITLE
Provide option to manage container snapshots

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2804]
We need to enable user to manage container snapshots via Console UI

**Comment by Dilshat** [comment]
How to test:
1. Create environment 
2. Go to Environment->Containers section and click Manage snapshots button next to container
![image](https://user-images.githubusercontent.com/3367326/53471294-578aec00-3a8e-11e9-8e0d-3bb3eaf3ff8a.png),
 a dialog will open
![image](https://user-images.githubusercontent.com/3367326/53471405-af295780-3a8e-11e9-85e6-c8d000e8bfc3.png)

3.Select a partition, enter a snapshot name and click Add
Result: a snapshot must be created:
![image](https://user-images.githubusercontent.com/3367326/53471480-ee57a880-3a8e-11e9-9e55-44527c4c5c04.png)

**Comment by Dilshat** [comment]
In a similar manner, test removal of snapshots

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
![screenshot from 2019-02-28 12-28-25](https://user-images.githubusercontent.com/9501291/53564199-7bc6f580-3b80-11e9-8cce-9e93d1ac5720.png)
![screenshot from 2019-02-28 17-43-30](https://user-images.githubusercontent.com/9501291/53564200-7bc6f580-3b80-11e9-8191-4665011e4d4f.png)
After selecting rollback option, the created file did not absent
![screenshot from 2019-02-28 17-45-16](https://user-images.githubusercontent.com/9501291/53564272-a0bb6880-3b80-11e9-8e23-4a0c5d6ce76b.png)
Test removal successfully tested

**Comment by kurmanbekova6** [comment]
Rollback option tested as well
![screenshot from 2019-02-28 18-02-19](https://user-images.githubusercontent.com/9501291/53565223-09a3e000-3b83-11e9-9dfe-2205a2ce4642.png)
Implemented in master

**Comment by Dilshat** [comment]
How to test:
1. Create environment 

2. Go to Environment->Containers section and click Manage snapshots button next to a container
![image](https://user-images.githubusercontent.com/3367326/53471294-578aec00-3a8e-11e9-8e0d-3bb3eaf3ff8a.png),
a dialog will open


(to be continued)

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
 ![screenshot from 2019-03-05 16-07-54](https://user-images.githubusercontent.com/9501291/53801836-6e3bb200-3f6a-11e9-8f19-e648a0dffabb.png)
![screenshot from 2019-03-05 16-08-32](https://user-images.githubusercontent.com/9501291/53801838-6ed44880-3f6a-11e9-832f-beba4a06c025.png)
![screenshot from 2019-03-05 16-29-07](https://user-images.githubusercontent.com/9501291/53801840-6ed44880-3f6a-11e9-9668-dc8b62417768.png)
First test case passed successfully
Only one thing made me confused
I did not type a name for snapshot and clicked add. There was created a snapshot "undefined" by default. (Is it correct behavior? ) I wanted to cancel that creation but there no any option to cancel.
![screenshot from 2019-03-05 17-18-41](https://user-images.githubusercontent.com/9501291/53802236-88c25b00-3f6b-11e9-974b-0f9022c5c7a5.png)

![screenshot from 2019-03-05 16-44-11](https://user-images.githubusercontent.com/9501291/53801898-9aefc980-3f6a-11e9-9ec7-1a9f7bbf869e.png)

9. Where I can select a partition for snapshots ?
![screenshot from 2019-03-05 17-23-38](https://user-images.githubusercontent.com/9501291/53802217-7b0cd580-3f6b-11e9-84fb-32e695a138b0.png)

**Comment by Dilshat** [comment]
@kurmanbekova6 
9. now partition selection is not possible
I will check the empty snapshot name

**Comment by Dilshat** [comment]
@kurmanbekova6 please retest

**Comment by kurmanbekova6** [comment]
Now we can't add a snapshot if snapshot's name is empty
![Screenshot from 2019-03-11 09-08-54](https://user-images.githubusercontent.com/9501291/54098126-5edebd80-43dd-11e9-8508-a780b2c6957c.png)
![Screenshot from 2019-03-11 09-09-17](https://user-images.githubusercontent.com/9501291/54098127-5edebd80-43dd-11e9-929e-cb1868775733.png)
Fixed in master

**Comment by fernandoted** [comment]
Can you unsubscribe me, me please?

**Comment by Dilshat** [comment]
@fernandoted you can do it yourself by clicking 
![image](https://user-images.githubusercontent.com/3367326/54114858-83568c00-4415-11e9-8025-2b6c4ff5a218.png)
