### ISSUE TITLE
Error while bringing peer up

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/peer-os#2805]
**Steps to reproduce:**

- Bring peer up.

Result:
![screenshot from 2019-02-20 16-45-02](https://user-images.githubusercontent.com/9501291/53086276-fe233a00-352e-11e9-9835-537abee3c761.png)
Only reload will help

**Comment by etursunbaev** [comment]
Confirm! Network inside management does not work

**Comment by kurmanbekova6** [comment]
@Dilshat Is there any news about this issue?
It is happening on both bazaars.

**Comment by Dilshat** [comment]
Currently I don't reproduce. Probably related with new vagrant

**Comment by Dilshat** [comment]
this is network issue
