### ISSUE TITLE
Hide snapshot prefixes used to prevent collisions

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2821]
We need to hide in Console UI snapshot name prefixes that will be used to differentiate individual snapshots (i-shots) from environment container snapshots (c-shots).
The prefixes are : **env-**

**Comment by kurmanbekova6** [comment]
Prefix is hidden from Console UI
![Screenshot from 2019-03-13 14-46-03](https://user-images.githubusercontent.com/9501291/54265117-c42ddc80-459e-11e9-9c42-6d6803776fc5.png)
@Dilshat  Is there any test case to test this issue?

**Comment by Dilshat** [comment]
How to test:
1. Create a local environment
2. For one environment container, create snapshots using agent
`subutai snapshot add -c {container} -p all -l env-all`
3. In Console UI view container snapshots in  Environment -> Containers section
Result: snapshots must be listed without prefix **env-**, i.e. **all** is displayed instead of **env-all** as a name of snapshot

**Comment by kurmanbekova6** [comment]
![Screenshot from 2019-03-13 15-02-41](https://user-images.githubusercontent.com/9501291/54266223-2851a000-45a1-11e9-9a9f-38e1690038b5.png)
Tested in master
