### ISSUE TITLE
Prevent users to prefix snapshots names with reserved prefixes

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2822]
We need to disallow using reserved prefixes in container snapshot names for individual snapshots (i-shots).
The reserved prefixes are: **env-**

**Comment by Dilshat** [comment]
How to test:
1. Create a local environment
2. In Environment -> Containers section, try to create a snapshot for an environment container, using **env-** as a prefix i.e. a snapshot name must start with **env-** ,e.g. **env-all**

Result: Snapshot creation must fail with an appropriate message

**Comment by kurmanbekova6** [comment]
![Screenshot from 2019-03-13 15-05-10](https://user-images.githubusercontent.com/9501291/54266410-87afb000-45a1-11e9-999d-c0abd53e2f4a.png)
Tested in master
