### ISSUE TITLE
Fix borked Karaf boot

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2827]
In rare cases, Karaf can not find config file `users.properties` and fails to load due to reaching the open file descriptor limit. https://github.com/apache/karaf/pull/382

We need to implement a workaround: a service that restarts Karaf when it has some of modules failed.
The service must call a REST that returns the state of Karaf boot.

**Comment by Dilshat** [comment]
How to test:

1. Create a fresh peer
2. Go to `System -> Advanced` section and run command `bundle:list`
3. Find bundle name `Subutai Local peer`
![image](https://user-images.githubusercontent.com/3367326/54796921-73904080-4c7c-11e9-8fe8-ffc572a86735.png)
4. Run command `bundle:stop {bundle-number}`, for example `bundle:stop 227`
5. Go to `Environment -> Tenants` section and observe that environments list is not loading
![image](https://user-images.githubusercontent.com/3367326/54797035-ca961580-4c7c-11e9-964f-020ab3b37d39.png)
6. Wait for 3 minutes and refresh the Tenants page
Result: Tenants page should show the environment list

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
![Screenshot from 2019-03-22 10-14-50](https://user-images.githubusercontent.com/9501291/54800306-6b8bcd00-4c8b-11e9-9a62-54dc26c4ceee.png)
![Screenshot from 2019-03-22 10-29-37](https://user-images.githubusercontent.com/9501291/54800684-6def2680-4c8d-11e9-9d98-25299576051e.png)
On tenants section environments was loading 5-8 min and showed the environments list
Not only tenants page was loading, after 2 minutes all Console was loading
My fresh peer 2 of 3 times went offline from bazaar side, but came back immediately.
After stopping bundle 227
![Screenshot from 2019-03-22 10-34-27](https://user-images.githubusercontent.com/9501291/54800957-b78c4100-4c8e-11e9-8602-de0543b0eaa8.png)
![Screenshot from 2019-03-22 10-09-29](https://user-images.githubusercontent.com/9501291/54800984-d985c380-4c8e-11e9-969f-ff01cce174b3.png)
